version: '2'
services:
  kanboard:
    image: kanboard/kanboard:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - kanboard_data:/var/www/app/data
      - kanboard_plugins:/var/www/app/plugins
      - kanboard_ssl:/etc/nginx/ssl
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: kanboard
      DATABASE_USER: kanboard
      DATABASE_PASSWORD: newPassword
    depends_on:
      - db
    links:
      - db:db
    restart: always

  db:
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - kanboard_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: newPassword
      MYSQL_DATABASE: kanboard
      MYSQL_USER: kanboard
      MYSQL_PASSWORD: newPassword
    restart: always

volumes:
  kanboard_data:
  kanboard_plugins:
  kanboard_ssl:
  kanboard_db: